### ISSUE TITLE
[ UI ] 新規作成ページの作成

### ISSUE THREAD

**Issue by Junkichi89** [if-mentor/next_todo_team_4#4]
## 実装内容の説明
- 新規作成のページの作成をお願いします。
- サイドバーとフォーム要素はコンポーネントとして実装予定なので、大体の実装でOKです。

## 実装予定のページ・コンポーネントのデザイン画像もしくはURL
![image](https://user-images.githubusercontent.com/65665381/159153444-9cec53cd-01fa-4606-82ea-c32ab1751876.png)

https://www.figma.com/file/0QdY0qOQSKpXn3gPsMNWXw/Untitled?node-id=32%3A158

## TASK
- [ ] pages配下に新規作成用のページを作成
- [ ] デザインに合わせて、見た目を作成したファイル上で実装する

**Comment by NeetOguma** [comment]
こちら完了いたしました。
修正箇所に関してはissueを立てて修正致します。
